# Generated by Django 4.1.4 on 2023-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='نویسنده',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
