# Generated by Django 4.1.4 on 2023-01-03 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0005_alter_product_title_in_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_article_نویسنده'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='نویسنده',
        ),
        migrations.AddField(
            model_name='article',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='product_services.category'),
        ),
    ]
