# Generated by Django 4.1.4 on 2023-01-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-add_time',)},
        ),
    ]
