# Generated by Django 4.1.4 on 2023-02-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('name', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('text', models.TextField()),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
