# Generated by Django 4.1.4 on 2023-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
