# Generated by Django 4.1.4 on 2023-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
