# Generated by Django 4.1.4 on 2023-02-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0003_alter_message_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('checked',)},
        ),
        migrations.AddField(
            model_name='message',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
