# Generated by Django 4.1.4 on 2022-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('camera', 'camera'), ('alarm', 'alarm'), ('gps', 'gps')], max_length=20, null=True)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='image/product')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('add_time', models.DateField(auto_now_add=True)),
                ('in_stock', models.BooleanField()),
                ('sells', models.IntegerField()),
                ('category', models.ManyToManyField(to='product_services.category')),
            ],
        ),
    ]
