# Generated by Django 4.1.4 on 2022-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
