# Generated by Django 4.1.4 on 2022-12-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_in_English',
            field=models.CharField(default=1, help_text='this filed is just for URLs , این بخش برای آدرس دهی این دوربین است.', max_length=100),
            preserve_default=False,
        ),
    ]
