# Generated by Django 4.1.4 on 2023-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0003_product_title_in_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product'),
        ),
    ]
