# Generated by Django 4.1.4 on 2023-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_in_English',
            field=models.CharField(help_text='به انگلیسی و با معنی و مفهوم مربوط به محصول پر شود! (میتوانید از نام محصول به انگلیسی استفاده کنید ) نباید تکراری باشد', max_length=100),
        ),
    ]
