# Generated by Django 4.1.4 on 2023-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0005_alter_product_title_in_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('svg_image', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-add_time',)},
        ),
    ]
