# Generated by Django 4.1.4 on 2023-01-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0007_remove_product_title_in_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.CharField(default=1, help_text='پیش نماش اطلاعات در کارت محصول', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='در صورتی که محصول موجود نیست تیک برداشته شود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(help_text='اطلاعات و توضیحات محصول'),
        ),
    ]
