# Generated by Django 4.1.4 on 2023-01-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0010_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image/product'),
        ),
    ]
