# Generated by Django 4.1.4 on 2023-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0012_service_preview_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product_services.category'),
        ),
    ]
