# Generated by Django 4.1.4 on 2023-01-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0013_service_image_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Description',
            new_name='info',
        ),
    ]
