# Generated by Django 4.1.4 on 2023-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0014_rename_description_service_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(choices=[('ABD', 'ABD'), ('SDF', 'SDF')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
