# Generated by Django 4.1.4 on 2023-01-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_services', '0015_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
